### ISSUE TITLE
Selecting module without any data loaded reports warning

### ISSUE THREAD

**Issue by jcfr** [mazurowski-lab/SlicerSegmentWithSAM#5]
Selecting the module without having any data loaded reports the following warning:

```pytb
Traceback (most recent call last):
  File "/path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/SegmentWithSAM.py", line 172, in setup
    self.initializeParameterNode()
  File "/path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/SegmentWithSAM.py", line 222, in initializeParameterNode
    volumeArray = slicer.util.arrayFromVolume(self._parameterNode.GetNodeReference("InputVolume"))
  File "/path/to/Slicer-Release/Slicer-build/bin/Python/slicer/util.py", line 1678, in arrayFromVolume
    vimage = volumeNode.GetImageData()
AttributeError: 'NoneType' object has no attribute 'GetImageData'
Traceback (most recent call last):
  File "/path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/SegmentWithSAM.py", line 185, in enter
    self.initializeParameterNode()
  File "/path/to/SlicerSegmentWithSAM-build/lib/Slicer-5.5/qt-scripted-modules/SegmentWithSAM.py", line 222, in initializeParameterNode
    volumeArray = slicer.util.arrayFromVolume(self._parameterNode.GetNodeReference("InputVolume"))
  File "/path/to/Slicer-Release/Slicer-build/bin/Python/slicer/util.py", line 1678, in arrayFromVolume
    vimage = volumeNode.GetImageData()
AttributeError: 'NoneType' object has no attribute 'GetImageData'
```

**Comment by Zaferyildiz** [comment]
If no data is added, the user is informed with a warning pop-up before they start segmentation. Thanks for the suggestion.
